### ISSUE TITLE
Remove output from the Notebook cells

### ISSUE THREAD

**Issue by sumit-goyal** [sumit-goyal/Watson-Studio-Workshop#14]
Please take out the output of the cells from the notebook. Users will see the results after cell execution

**Comment by sumit-goyal** [comment]
Notebook: https://github.com/sumit-goyal/Watson-Studio-Workshop/blob/master/notebooks/Part%201_%20Use%20Spark%20and%20Python%20to%20Predict%20Equipment%20.ipynb

**Comment by Maiti0112358** [comment]
implemented by: https://github.com/sumit-goyal/Watson-Studio-Workshop/pull/16
